### ISSUE TITLE
breadcrumb.tpl - block name conflict

### ISSUE THREAD

**Issue by damiweb** [PrestaShop/classic-rocket#104]
The same name of block is used in layout (layoyt-both-columns.tpl). It is problematic in case we want to override layout breadcrumb block in descendant templates.

https://github.com/PrestaShop/classic-rocket/blob/3c799c4bd8d5fce7addf87a5d205e6791880b75f/templates/_partials/breadcrumb.tpl#L28

https://github.com/PrestaShop/classic-rocket/blob/3c799c4bd8d5fce7addf87a5d205e6791880b75f/templates/layouts/layout-both-columns.tpl#L57

My advice is to change the name of block in breadcrumb.tpl, because it is rarely overridden.

**Comment by micka-fdz** [comment]
Proposed PR : #108
