### ISSUE TITLE
Page scrolling improvement on pagination and changing filters

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/classic-rocket#107]
Hi @prestarocket, I have some suggestions regarding page scrolling on product list update.

**Current situation**
Page scrolls all the way to the top whenewer you change product listing page or change some filters. This is not very user intuitive and when I want to make some selection in faceted search, I have to scroll down to filters all the time.

**My proposed solution**
Clicking top pagination - do not scroll
Clicking bottom pagination - scroll to the top of the product list
Changing filters in faceted search - do not scroll

**Comment by prestarocket** [comment]
could you make a PR ?
