### ISSUE TITLE
material icon abandoned, move to another alternatives?

### ISSUE THREAD

**Issue by dosbiner** [PrestaShop/classic-rocket#114]
I like material icons, but there are no updates for long time, I think this project abandoned as official said here https://github.com/google/material-design-icons/issues/786#issuecomment-403215569

Maybe move to another alternatives?

**Comment by PrestaShark** [comment]
Only https://github.com/FortAwesome/Font-Awesome guys.
Im using PRO version - they are awesome.

**Comment by Hlavtox** [comment]
Font Awesome is beautiful, but resource intensive...

**Comment by prestarocket** [comment]
font awesome is too heavy. We are waiting bootstrap icon ready
