### ISSUE TITLE
Why BEM?

### ISSUE THREAD

**Issue by redactuk** [PrestaShop/classic-rocket#116]
I'm curious why the move to BEM when Prestashop is predominantly based on Bootstrap?

I have used BEM on some projects, but only where whole project uses it. What I don't understand is why use it when parent or base project does not. To me it's a confusing mix.

In last classic-rocket version we stripped it out and replace BEM classes, reverting back to using Boostrap, simply because it seems to overlap unnecessarily with bootstrap, with lots of instances of duplication.

Of course you are free to do whatever you want. I just wanted to understand why the need for it.

Thanks

**Comment by prestarocket** [comment]
Hello @redactuk , we want to use BEM on specific components; for ex., on product cards, product cart line etc..
if the use of BS class is usefull, we could extend it. 
The goal is to make the theme easier to maintain
