### ISSUE TITLE
Source maps are not working correctly

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/classic-rocket#118]
Steps to reproduce:

1. install fresh copy of the classic-rocket
2. yarn install everything
3. yarn run gulp watch
4. modify `theme.scss`
5. add this code:
```
body {
    background: pink !important;
}
```

6. save, wait for a compilation
7. refresh and see if devtools are pointing to correct .scss file, result? no, they're not pointing to the right file

**Comment by prestarocket** [comment]
it s ok now with https://github.com/PrestaShop/classic-rocket/commit/2238019e33261d9cd2469d8b9e9010d225017ab3
