### ISSUE TITLE
Scattered strange files in assets/css

### ISSUE THREAD

**Issue by dangelion** [PrestaShop/classic-rocket#145]
Inside `assets/css` there's a lot of scattered files with strange filenames. They are fonts, images, etc. I don't think that kind of files should be placed inside css folder. Check the attached screenshot.

![Schermata 2020-03-25 alle 19 20 51](https://user-images.githubusercontent.com/4182418/77737313-03926400-700e-11ea-9f22-f4df639834a1.jpg)

**Comment by prestarocket** [comment]
it s the default webpack config of Prestashop
