### ISSUE TITLE
Copy images from _dev/img to assets/img

### ISSUE THREAD

**Issue by dangelion** [PrestaShop/classic-rocket#147]
Hi
when I add images in `_dev/img` they're not automatically copied to `assets/img`.
Same if I re-run `npm run watch` or `npm run build`.
I'd avoid to manually copy them...
Is it a bug or something? How solve it?

**Comment by prestarocket** [comment]
Hi, they are copied when it s used in scss (ex : bg img)

**Comment by dangelion** [comment]
I use images in HTML, and for that they're not copied

**Comment by dangelion** [comment]
I think this need to be re opened and should implemented, any framework/starter theme has it. Copying images from dev folder to assets folder
