### ISSUE TITLE
crashed instalaltion

### ISSUE THREAD

**Issue by Macrisu** [PrestaShop/classic-rocket#149]
I have a new Prestashop 1.7.6.2 (newest) instalaltion that I try to learn and I tried to use this theme.
I've installed the theme and I tried to apply, but Error 500 on all may site.

Now how can I revert to the original, default theme?

**Comment by prestarocket** [comment]
set mode debug on to show errors

**Comment by Macrisu** [comment]
Set where?
I get error 500

**Comment by prestarocket** [comment]
config/defines.inc.php set debug mode true : define('_PS_MODE_DEV_', true);

**Comment by Macrisu** [comment]
Now It works.

I suspect that I needed to disable cache and all non-prestashop modules when I tried to apply the new theme.

**Comment by Macrisu** [comment]
I've spoke too soon
Warning: require_once(/var/www/xxxxx/var/cache/dev/appParameters.php): failed to open stream: Permission denied in /var/www/xxxxx/config/bootstrap.php on line 87

> Fatal error: require_once(): Failed opening required '/var/www/xxxxx/var/cache/dev/appParameters.php' (include_path='/var/www/xxxxx/vendor/pear/pear_exception:/var/www/xxxxx/vendor/pear/console_getopt:/var/www/xxxxx/vendor/pear/pear-core-minimal/src:/var/www/xxxxx/vendor/pear/archive_tar:.:/usr/share/pear:/usr/share/php') in /var/www/xxxxx/config/bootstrap.php on line 87

**Comment by prestarocket** [comment]
I don't think it's because of the theme.
