### ISSUE TITLE
Product page: Changing quantity or size reloads product image

### ISSUE THREAD

**Issue by mortenhartvig** [PrestaShop/classic-rocket#15]
When you update the quantity from say 1 to 2, there is no reason for showing the image loading spinner, and replacing it with the current image again (image reload).

Re-loading an image:
- ok, when changing color etc.  👍 (this works fine)
- not ok, when changing the **quantity** or **size** 🐛 (this should be changed)

**Comment by prestarocket** [comment]
it is not handled by the theme but by ProductController and core.js: https://github.com/PrestaShop/PrestaShop/blob/1.7.4.x/controllers/front/ProductController.php#L398

**Comment by mortenhartvig** [comment]
Blinking images on a white background is bad for everything, including - and not limited to - epilepsy:)

It's not a bug/feature in "native", because it becomes a bug/feature when you add lazy-loading the way this theme does. I currently use lazy-loading with mod_pagespeed for a "prestashop_classic" fork, and even though it behaves worse, it dosn't flickr the images, as it checks if the file is the same before changing:)

Instead of replacing existing (loaded) images with the loading-spinner. Just append the spinner on top of the existing (loaded) image with a higher z-index or similar solution, where you don't replace an image with a blank background. 

Please, for the sake of epilepsy, and UX in general. :)

I may add it at some point and do a pull-request/fork, when i update my production shop to 1.7.4.x, but that may take months due to no time.

**Comment by prestarocket** [comment]
i'm not sure to understand your point but i can remove lazyloading only for the first product img (it s always in the viewport) in order to remove this blinking effect; what do you think about it ?
