### ISSUE TITLE
 A non well formed numeric value encountered Error in microdata-jsonld.tpl

### ISSUE THREAD

**Issue by alexmixaylov** [PrestaShop/classic-rocket#150]
After installing the theme I get an error when trying to redirect on the product page
`Notice: A non well formed numeric value encountered`
row 133  "priceValidUntil": "{($smarty.now + (60\*60\*24\*15))|date_format:"%Y-%m-%d"}",
in the templates/_partials/microdata-jsonld.tpl
It may fixed if convert string to integer value, for example 
`"priceValidUntil": "{$smarty.now + (int) (60*60*24*15)|date_format:"%Y-%m-%d"}",`

**Comment by prestarocket** [comment]
with demo prestashop product ?

**Comment by alexmixaylov** [comment]
> with demo prestashop product ?
No, with the custom product.
I use PHP7.1 and turn on Debug mode. 
(60*60*24*15))|date_format:"%Y-%m-%d" - this expression return string
$smarty.now return integer value
in  PHP 7  this causes an error

**Comment by prestarocket** [comment]
could you create a PR on branch dev with your fix ?

**Comment by alexmixaylov** [comment]
OK, I have done it

**Comment by prestarocket** [comment]
done
