### ISSUE TITLE
header issues with new Release 2.1.5 - PrestaShop 1.7.6.5

### ISSUE THREAD

**Issue by etsmes** [PrestaShop/classic-rocket#155]
Dears,

With the new version I cannot correctly align the header menu (line breaks appear).
I have tried some changes in the css stylesheet but nothing works for me anymore.
Also, adding the carousel in _displayNavFullWidth_ does not work correctly (a new margin or padding has appeared in the header)

I really appreciate your help

###  **screenshot with the previous version**

![header-old](https://user-images.githubusercontent.com/19926260/81043307-52a3a280-8eb2-11ea-9d8d-02de4aea19da.PNG)

### **screenshot with the new version**

![header-new](https://user-images.githubusercontent.com/19926260/81043317-546d6600-8eb2-11ea-8ae8-55e6d50fa076.PNG)

**Comment by jaszpol** [comment]
same problem. 

![image](https://user-images.githubusercontent.com/64835152/81049862-525dd400-8ebf-11ea-9174-2b741c0975da.png)
We are waiting for help :)
