### ISSUE TITLE
FEATURE REQUEST - MEGA MENU

### ISSUE THREAD

**Issue by By-oussef** [PrestaShop/classic-rocket#17]

**Comment by prestarocket** [comment]
We are working on a new module menu. Can you give us what exactly do you need ?

**Comment by By-oussef** [comment]
I wish that in the menu I can add fontawesome icons from the backend: for example I have a category shows I add this icon : https://fontawesome.com/icons/watch?style=regular

For the clothing category this icon: https://fontawesome.com/icons/tshirt?style=solid
...

I want the menu to be responsive design and it is possible to change the color from the backend.

**Comment by prestarocket** [comment]
Not in this free theme. We are working in a simple menu module
