### ISSUE TITLE
Feature Request - seller's warranty

### ISSUE THREAD

**Issue by By-oussef** [PrestaShop/classic-rocket#18]
Add these items to the theme to reassure the customer and encourage them to buy.

FREE SHIPPING - MONEY BACK - DISCOUNTS - SUPPORT

![stu](https://user-images.githubusercontent.com/41373170/49303638-84008d80-f4ca-11e8-9715-ade3080e642a.png)

**Comment by duGuillaume** [comment]
This is not the theme of doing this, you can do that with {hook h='displayFooterBefore'}
this kind of feature request an admin configuration
