### ISSUE TITLE
Feature Request - Add multiple predefined color.

### ISSUE THREAD

**Issue by By-oussef** [PrestaShop/classic-rocket#19]
currently the theme is founit with pretty simple colors: blue, white and gray. It would be interesting to add several shades of colors modifiable from the backend. Because all users do not have the same tastes. Some prefer soft colors others brighter and brighter colors others darker.

**Comment by prestarocket** [comment]
The goal of this theme is to keep it closest to the default theme classic; you can edit colors in variables.scss. We are also working on premium theme with this kind of feature.
