### ISSUE TITLE
Carousel images not sliding

### ISSUE THREAD

**Issue by apcloic** [PrestaShop/classic-rocket#23]
Hi,

It looks like there is no automatic image rotation on classic-rocket carousel slider, reproductible on the demo site.
https://demo-prestashop.prestarocket.com/
Regards,

**Comment by duGuillaume** [comment]
here from the doc autoplay | boolean | false | Enables Autoplay

did you tried to put autoplay:true into theme.js line 69 (don't forget to build assets)?
```
slickSlider.init({
  autoplay: true
});
```

**Comment by prestarocket** [comment]
You should add 

> `<div id="carousel" data-slick='{ldelim}"autoplay": true{rdelim}'...`

in themes/classic-rocket/modules/ps_imageslider/views/templates/hook/slider.tpl

**Comment by apcloic** [comment]
Thank you both !
I've modified slider.tpl as suggested, it works perfectly now.
Best regards,
