### ISSUE TITLE
module ps_searchbarjqauto invalid prestashop 1.7.5.0

### ISSUE THREAD

**Issue by pierre31ess** [PrestaShop/classic-rocket#33]
Hello
thanks for your theme... really....
but i cannot install it because prestashop 1.7.5.0 tell me that invalid module so unable to install it 
can you please help me
thanks

**Comment by prestarocket** [comment]
Hello,

did you try this zip : https://github.com/PrestaShop/classic-rocket/releases/download/2.1.0/classic-rocket.zip

**Comment by dam62500** [comment]
still same for me

**Comment by ashdicolor** [comment]
Hello Thank you for your great work on classic-rocket. 
I have the same issue with Prestashop version 1.7.6.1, the same message about this module.
Thank you for your help.

**Comment by dangelion** [comment]
Same problem here on Prestashop 1.7.6.4. After activate the theme it says impossible to instala the module ps_searchbarjqauto, it's not valid.

How to solve?

**Comment by prestarocket** [comment]
add ps_searchbarjqauto in modules directory

**Comment by AurelienDud** [comment]
Same problem for me with Classic-rocket v3.0.4 on PrestaShop 1.7.7.0.
ps_searchbarjqauto module already exist in the directory. 
The issue isn't that the module is not found but invalid. 

That issue is now closed but was it solved? If yes what is the solution? 

Thanks
