### ISSUE TITLE
Footer copyright info not centered on small screens

### ISSUE THREAD

**Issue by johanlantz** [PrestaShop/classic-rocket#34]
This is a minor, just mentioning it here since I do not know all the places where text-sm-center.

The css:

@media (min-width: 576px)
.text-sm-center {
    text-align: center!important;
}

Does not center the copyright text on screens smaller than 576px, I think the intention is that it should be centered?

Reproduce by simply making the screen smaller than 576px and see that the copyright info etc is moved from the center to the left.

**Comment by SharakPL** [comment]
I recommend reading something about media breakpoints and how their pointers (xs, sm, md, lg, xl) are used throughout bootstrap 4. [Here's about text alignement.
](https://getbootstrap.com/docs/4.2/utilities/text/#text-alignment)
Change class from `text-sm-center` to `text-center` in related .tpl file to have it always centered.

**Comment by johanlantz** [comment]
Thanks for taking the time to comment, I just put the issue here so the main developer can choose if he wants to fix it the way he prefers.

**Comment by prestarocket** [comment]
i will fix in the next release
