### ISSUE TITLE
Issues in google product structured data 

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/classic-rocket#36]
On product page, there are some issues in google product structured data :
- There are two versions : a json-ld version and old microdata version 
- With the google tool https://search.google.com/structured-data/testing-tool there are some warnings that has to be fixed.

**Comment by SuperArnaud** [comment]
On classic-rocket\templates\catalog\_partials\miniatures\product.tpl
1. Add image by setting an itemprop and content
`{if $product.cover}
<img data-src = "{$product.cover.bySize.home_default.url}" alt = "{if !empty($product.cover.legend)}{$product.cover.legend}{else}{$product.name|truncate:30:'...'}{/if}" data-full-size-image-url = "{$product.cover.large.url}" class="lazyload" itemprop="image" content="{$product.cover.bySize.home_default.url}">`

2. Add category
`<meta itemprop="category" content="{$product.category_name}">`

3. Add brand
`{if isset($product_manufacturer->id)}<meta itemprop="brand" content="{$product_manufacturer->name}">{/if}`

4. Add Offer
`<div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
<meta itemprop="availability" content="{if $product.available_for_order}InStock{else}OutOfStock{/if}">
<meta itemprop="price" content="{$product.price_amount}">
<meta itemprop="priceCurrency" content="{$product.currency}">
<meta itemprop="url" content="{$product.url}">
</div>`

**Comment by jf-viguier** [comment]
Your suggestion is for and old microdata version, the recommanded way from google is by using json-ld version.
The microdata version should be removed.

**Comment by SuperArnaud** [comment]
Right! 
Remove all itemscope/itemprop/content and edit classic-rocket\templates\_partials\microdata-jsonld.tpl

Add cover image to the product JSON
`"image": "{$product.cover.bySize.home_default.url}",`
Add priceValidUntil to Offer (15 days)
`"priceValidUntil": "{$smarty.now + (60*60*24*15)|date_format:"%Y-%m-%d"}",`
Add url to Offer
`"url": "{$product.url}",`

Hope it will help

**Comment by johanlantz** [comment]
Will these changes make it into the the next official release? Would be nice to only have the json-ld

**Comment by tameroski** [comment]
I'd like to add that the $product variable should be tested before rendering any product related jsonld, because it's not set when the customer is not allowed on the product category : 

`{if  isset($product) && $page.page_name == 'product'}`

My 2 cents.

**Comment by prestarocket** [comment]
> Will these changes make it into the the next official release? Would be nice to only have the json-ld

=> yes

**Comment by dvir-yadai** [comment]
hi,


> Right!
> Remove all itemscope/itemprop/content and edit classic-rocket\templates_partials\microdata-jsonld.tpl
> 
> Add cover image to the product JSON
> `"image": "{$product.cover.bySize.home_default.url}",`
> Add priceValidUntil to Offer (15 days)
> `"priceValidUntil": "{$smarty.now + (60*60*24*15)|date_format:"%Y-%m-%d"}",`
> Add url to Offer
> `"url": "{$product.url}",`
> 
> Hope it will help

hi,
in prestahop 1.6.1.23 im not getting a valid date : 
<meta itemprop="priceValidUntil" content="1556392063">

in product.tpl : 
<meta itemprop="priceValidUntil" content="{$smarty.now + (60*60*24*15)|date_format:"%Y-%m-%d"}">

why i cant get a valid date ?

**Comment by przemokon** [comment]
> hi,
> in prestahop 1.6.1.23 im not getting a valid date :
> in product.tpl :
> <meta itemprop="priceValidUntil" content="{$smarty.now + (60_60_24*15)|date_format:"%Y-%m-%d"}">
> 
> why i cant get a valid date ?

Hi,
you need to wrap {$smarty.now + (60*60*24*15)|...} in brackets. There can't be blank spaces.
<meta itemprop="priceValidUntil" content="{($smarty.now + (60*60*24*15))|date_format:"%Y-%m-%d"}">

**Comment by xsbr** [comment]
After upgrade PHP to 7.3 version I found this notice (debug mode):
```
(1/1) ContextErrorException
Notice: A non well formed numeric value encountered
```

So I fixed it using @przemokon suggestion to wrap in brackets:

**From:**
`<meta itemprop="priceValidUntil" content="{$smarty.now + (60*60*24*15)|date_format:"%Y-%m-%d"}">`

**To:**
`<meta itemprop="priceValidUntil" content="{($smarty.now + (60*60*24*15))|date_format:"%Y-%m-%d"}">`
