### ISSUE TITLE
Footer does not expand on iphone

### ISSUE THREAD

**Issue by johanlantz** [PrestaShop/classic-rocket#37]
On iPhone the small arrows to the right in the footer:
<img width="464" alt="screenshot 2019-02-02 at 18 11 31" src="https://user-images.githubusercontent.com/7461655/52660527-22b05e00-2f00-11e9-8264-374665cf5b7b.png">

does not expand. It works works in other browsers and also on Android but not in iOS. Nothing happens when clicking the arrow so the footer menu options does not display.

**Comment by SuperArnaud** [comment]
I think your picture is not related to the bug.
To fix it: classic-rocket\modules\ps_linklist\views\templates\hook\linkblock.tpl
Set a <a href="#footer_sub_menu_{$_expand_id}" instead of a <div> block.

Same fix for all div which has data-toggle="collapse" (eg. facets)

**Comment by prestarocket** [comment]
Maybe button will be better
