### ISSUE TITLE
Images on product page not loading.

### ISSUE THREAD

**Issue by morfin** [PrestaShop/classic-rocket#39]
Prestashop v1.7.4.2
classic-rocket 1.0.0

Classic theme loads images correctly with following URL:
http://localhost:8081/135-large_default/my_product.jpg

classic-rocket tries to load image with following URL (which points to nowhere):
http://localhost:8081/135-pdt_540/my_product.jpg

This happens when changing theme from classic to classic-rocket.

I way to fix this would be to manually rename pictures on the server.

Is there any other way?

Thanks.

**Comment by prestarocket** [comment]
do you have in your BO, image type pdt_540 ?

**Comment by dangelion** [comment]
Same problem here. How can restore the images?

**Comment by prestarocket** [comment]
yes
