### ISSUE TITLE
Slow loading of Material Icons Font

### ISSUE THREAD

**Issue by Fabuloops** [PrestaShop/classic-rocket#43]
Hello,

The icons loading of the google font was too slow, the text appeared before the icons. So i changed the loading. Instead of using the file font.tpl, i load the Material Icons Font with the _font.scss file like that :
```
@import url('https://fonts.googleapis.com/css?family=Montserrat:400,700');
```
That's solved my problem. Hope it will help someone else.

**Comment by PrestaShark** [comment]
This is not a good idea...
https://www.google.com/search?client=firefox-b-d&q=avoid+%40import

IMHO something was wrong with Your internet connection.

**Comment by dosbiner** [comment]
I can confirm this issue, my pagespeed test show this warning:

_Ensure text remains visible during webfont load_
URL                                                               Potential Savings (ms)
fonts.gstatic.com/s/materialicons/....                       150ms
fonts.gstatic.com/s/notosans/....                              150ms
fonts.gstatic.com/s/notosans/....                              150ms

there is solution https://web.dev/fast/avoid-invisible-text
but I don't know how to implement this

**Comment by prestarocket** [comment]
we didn't use anymore google font for material. We will use local material font

**Comment by dosbiner** [comment]
thank you, better and faster. but make sure to delete all code inside templates/_partial/font.tpl
