### ISSUE TITLE
Image Slider auto transition not working

### ISSUE THREAD

**Issue by morfin** [PrestaShop/classic-rocket#44]
Hi, 

Not even the official demo site is working. By default the slide should transition every 5000ms. That's not happening. Any idea?

**Comment by dosbiner** [comment]
+1
I can confirm this bug

**Comment by prestarocket** [comment]
i wll fix it in the next release;
in modules/ps_imageslider/views/templates/hook/slider.tpl, you can add :
`  <div id="carousel" class="carousel slick__arrow-large" {if $homeslider.slides|count > 1}data-slick={strip}
  '{literal}{
  "autoplay": true,
  "slidesToShow": 1,
  "autoplaySpeed":{/literal}{$homeslider.speed}{literal},
  "dots": true

  }{/literal}'
          {/strip}{/if}>`

**Comment by prestarocket** [comment]
done
