### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/classic-rocket#45]
Hey @prestarocket 

i've noticed that progress here is slow and classic-rocket becomes outdated, do you need some help to maintain this project?

**Comment by prestarocket** [comment]
Hello Krystian,
We're planning to work on it next week; we've been a little busy these past few weeks. But with pleasure for help, I'll send you an email.
we have put online a beautiful project based on classic rocket : https://www.koziel.fr/fr/
