### ISSUE TITLE
ps_facetedsearch 3.0.x template

### ISSUE THREAD

**Issue by PrestaShark** [PrestaShop/classic-rocket#55]
After latest upgrade of reworked ps_facetedsearch template need to be upgraded too.
Reason? No toggler visible in desktop view, two togglers (up,down) visible in mobile. also break the lines

![tog_desk](https://user-images.githubusercontent.com/8243273/58689531-8ebbb280-8387-11e9-9452-9ac6204f877c.jpg)
![toggler](https://user-images.githubusercontent.com/8243273/58689532-8f544900-8387-11e9-9aad-f3c46686eb85.jpg)

**Comment by redactuk** [comment]
With clean Prestashop 1.7.5.2 and classic-rocket 2.1.2 and faceted search upgraded to 3.0.2 Faceted search dissappears completely for me. Tried delete custom template override and made no difference.

In addition (and probably related) filtering by price with standard filter fails to show any records.

**Comment by prestarocket** [comment]
we will fix it next week

**Comment by PrestaShark** [comment]
![zrzut 2019-06-21 13 03](https://user-images.githubusercontent.com/8243273/59918553-560e7680-9425-11e9-88ae-8fafc8b56f61.jpg)

fixed

**Comment by PrestaShark** [comment]
also in modal

![modal](https://user-images.githubusercontent.com/8243273/59918621-8fdf7d00-9425-11e9-9519-ea6da573ca26.jpg)

**Comment by mootookoi** [comment]
Thank you =)
