### ISSUE TITLE
Issue on products display

### ISSUE THREAD

**Issue by msaustral** [PrestaShop/classic-rocket#56]
Hi on less than 320 px width it keeps showing 2 columns (col-6) it should be col-12
![image](https://user-images.githubusercontent.com/46203943/59117460-c8f2fa00-891b-11e9-9089-4f21b22bc281.png)

**Comment by msautral** [comment]
The solution!
![presta1](https://user-images.githubusercontent.com/46203943/59117976-14f26e80-891d-11e9-9536-e8550df9c0f7.png)
![presta2](https://user-images.githubusercontent.com/46203943/59117986-1ae84f80-891d-11e9-892a-ad04ab03fa37.png)
![presta3](https://user-images.githubusercontent.com/46203943/59117993-1fad0380-891d-11e9-94d5-63457dd71387.png)
