### ISSUE TITLE
Feature request - Link modules positions to active theme

### ISSUE THREAD

**Issue by thsantac** [PrestaShop/classic-rocket#57]
Hi,

I've been developing e-commerce websites with PS (from 1.5 to 1.7) for years now. 

Yesterday my boss wanted to see how looks the classic theme. So, being currently working on a new PS website (1.7.5.2), I switched from my current "under development" theme to classic one and showed how it looks to my boss. But when I wanted to go back to my working theme, all modules positions were initialized, so I had to do gain all I did to get my theme working correctly.

This is where I wanted to go: could it be nice to link all modules positions to the active theme? This way a switch between two themes could be easier and would not break the website. I think the "Home page configuration" should also been linked to the active theme.

Thanks.

**Comment by prestarocket** [comment]
could it be done only in the theme config ?
