### ISSUE TITLE
Issue with colissimo module

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/classic-rocket#59]
The colissimo modal box for choosing relay points is not clickable.
The div div .modal-content is missing in colissimo template.

In classic rocket, there is a “pointer-events: none” on .modal-dialog and “pointer-events: auto” on .modal-content

How can we fix that ?

**Comment by PrestaShark** [comment]
Hi. IMHO module should be template independent.

Module developers should look into rather than classic-rocket developers, to make Boostrap 4+ compatbility or ensure interoperability

**Comment by tameroski** [comment]
Hi,
I had the same issue with their plugin. They're working on a fix for the next rework of the plugin.

You can fix this by overriding a few styles in your theme (ex. in scss) :
```
.colissimo-front-widget{

  &.fade.in {
    opacity: 1 !important;
  }

  .modal-dialog {
    pointer-events: auto !important;
    transform: translateY(0) !important;
  }
}

.modal.fade .modal-dialog {
  transform: translateY(0) !important;
}
```
