### ISSUE TITLE
how to keep changes after updates?

### ISSUE THREAD

**Issue by backamblock** [PrestaShop/classic-rocket#6]
Hello there, i write changes to the custom.css, but after update the files are deleted.. is there a way to update keeping changed files or even changed code easily?

greetings

**Comment by prestarocket** [comment]
maybe with git update-index --assume-unchanged FILE_NAME

**Comment by prestarocket** [comment]
or $ git update-index --skip-worktree FILENAME

**Comment by backamblock** [comment]
ok, i will find out how and where to do what you said, thanks👍
