### ISSUE TITLE
Overlay problem with megamenu and slider

### ISSUE THREAD

**Issue by MortenKL** [PrestaShop/classic-rocket#60]
On Desktop, when the megamenu window overlaps the slider, in the front page, the slider control buttons < .. > are on top, so you cannot click on the menu items, and the menu will disappear when hovering over the slider buttons.
![Skærmbillede 2019-06-18 kl  13 46 55](https://user-images.githubusercontent.com/3610705/59679858-3cc0bc80-91d0-11e9-98cf-e84fe37498eb.png)

**Comment by PrestaShark** [comment]
theme.css 
from:

.slick-arrow{position:absolute;top:0;height:100%;display:flex;flex-direction:column;justify-content:center;padding-top:0;padding-bottom:0;z-index:**2**}

to:

.slick-arrow{position:absolute;top:0;height:100%;display:flex;flex-direction:column;justify-content:center;padding-top:0;padding-bottom:0;z-index:**1**}

**Comment by MortenKL** [comment]
That'll do it - thanks a lot!, fixed in the minified css.
But It should probably be fixed in /css/components/slick-theme.scss - along the way. 
Leaving it open for now.
