### ISSUE TITLE
Question: 1.7.6 status

### ISSUE THREAD

**Issue by johanlantz** [PrestaShop/classic-rocket#71]
Just a question, not an issue.

Will there be a release of classic-rocket matching the 1.7.6 release of Prestashop?

**Comment by prestarocket** [comment]
yes we are already work on it

**Comment by johanlantz** [comment]
Really happy to hear that, you are doing an awesome job.
Any estimation on when the updates for 1.7.6 will be ready? I would be happy to help testing.

**Comment by prestarocket** [comment]
we are working hard to update it today

**Comment by johanlantz** [comment]
any status update to share 😊

**Comment by johanlantz** [comment]
🙏 would be very helpful to know if you are close or if it will be a longer delay.

It is fine either way, you are great working on this awesome theme it's just that I'm very close to starting my shop and the only thing missing is to use this theme.

**Comment by prestarocket** [comment]
I need 2 more days

**Comment by johanlantz** [comment]
Thanks for the info.

I am happy to test a beta version on my test shop if it can help you wit the QA.

**Comment by johanlantz** [comment]
Any update on the expected release date for us impatiently waiting  😄

**Comment by matks** [comment]
@prestarocket it seems you have a very motivated users group 😄 🎉

**Comment by jf-viguier** [comment]
On on t'attends de pied ferme chez nous aussi, merci à toi.

**Comment by johanlantz** [comment]
Is the develop branch ok to use while waiting for the release or are there major changes pending that are not yet visible on github?

**Comment by jf-viguier** [comment]
Des news de la maj 1.7.6 ?

**Comment by bhavikvaghani** [comment]
Do you have set any deadline for 1.7.6 compatibility?
