### ISSUE TITLE
megamenu not wrapping

### ISSUE THREAD

**Issue by MortenKL** [PrestaShop/classic-rocket#72]
When a category holds more than a certain number of subcategories, the text does not stay within the border of the menu box. Ideally it should wrap around and continue downwards inside the box (I would imagine). 
![Skærmbillede 2019-07-03 kl  09 04 30](https://user-images.githubusercontent.com/3610705/60571926-c2b63900-9d74-11e9-8e42-de7193191fff.png)

**Comment by MortenKL** [comment]
I was able to get by with this css:
`@media (min-width:768px){
        ul.menu-sub__list--1 {
                flex-wrap:wrap;
        }
        li.menu__item--1 {
                margin-bottom:15px;
        }       
} `
Not entirely sure if this is the best solution, but seems to do the trick.

**Comment by prestarocket** [comment]
this theme is not designed to have a menu with many items

**Comment by MortenKL** [comment]
As I said, it’s solved by a simple css rule.
Even if you don’t think it is designed to have many items it actually can have more, and I just showed you how to do it without a problem.

 - well, guess that's your call then ;-)


/Morten
