### ISSUE TITLE
Issue when update to webpack 4 and all plugins

### ISSUE THREAD

**Issue by msaustral** [PrestaShop/classic-rocket#75]
Hi there is an issue when you update to webpack 4 and all plugins and dependencies, here is the new webpack configuration:

### **webpack.config.js**
`/**
 * 2007-2017 PrestaShop
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License 3.0 (AFL-3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/AFL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future. If you wish to customize PrestaShop for your
 * needs please refer to http://www.prestashop.com for more information.
 *
 * @author    PrestaShop SA <contact@prestashop.com>
 * @copyright 2007-2017 PrestaShop SA
 * @license   https://opensource.org/licenses/AFL-3.0 Academic Free License 3.0 (AFL-3.0)
 * International Registered Trademark & Property of PrestaShop SA
 */
const webpack = require('webpack');
const path = require('path');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const TerserPlugin = require('terser-webpack-plugin');

let config = {
  optimization: {
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          sourceMap: true,
          compress: {
            sequences: true,
            conditionals: true,
            booleans: true,
            if_return: true,
            join_vars: true,
            drop_console: true
          },
          output: {
            comments: true
          },
          minimize: false
        },
      }),
    ],
  },
  entry: {
    main: [
      './js/theme.js',
      './css/theme.scss'
    ]
  },
  output: {
    path: path.resolve(__dirname, '../assets/js'),
    filename: 'theme.js',
    sourceMapFilename: '[file].map'
  },
  devtool: 'source-map',
  plugins: [
    new MiniCssExtractPlugin({
      // Options similar to the same options in webpackOptions.output
      // both options are optional
      filename: '../css/theme.css',
    }),
  ],
  module: {
    rules: [
      {
        test: /\.js/,
        loader: 'babel-loader'
      },
      {
        test: /\.(sa|sc|c)ss$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              sourceMap: true
            }
          },
          {
              loader: 'css-loader',
              options: {
                    sourceMap: true
                  }
          },
          {
            loader: 'postcss-loader',
            options: { 
                sourceMap: true, 
                   plugins: function() { 
                        return [ require('autoprefixer') ] 
                   }
              }
          },
          {
            loader: 'sass-loader',
            options: { sourceMap: true }
          }
          
        ],
      },
      {
        test: /.(png|woff(2)?|eot|ttf|svg|gif)(\?[a-z0-9=\.]+)?$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '../css/[hash].[ext]',
              sourceMap: true
            }
          }
        ]
      }
    ]
  },
  externals: {
    prestashop: 'prestashop',
    $: '$',
    jquery: 'jQuery'
  }
};

module.exports = config;
`
### **package.json**
`{
  "name": "xxxxxxx",
  "version": "1.0.0",
  "description": "Tema de xxxxxx",
  "main": "index.js",
  "scripts": {
    "build": "webpack --mode production --progress --colors --debug --display-chunks",
    "watch": "webpack --mode development --progress --colors --debug --display-chunks --watch"
  },
  "author": "Ausral",
  "license": "AFL-3.0",
  "devDependencies": {
    "@babel/core": "^7.5.4",
    "ajv": "^6.9.1",
    "autoprefixer": "^9.4.4",
    "babel-loader": "^8.0.6",
    "bootstrap": "4.3.1",
    "bootstrap-touchspin": "^4.2.5",
    "css-loader": "^3.0.0",
    "expose-loader": "^0.7.3",
    "file-loader": "^4.0.0",
    "flexibility": "^1.0.5",
    "gulp": "^4.0.0",
    "gulp-autoprefixer": "^6.0.0",
    "gulp-replace": "^1.0.0",
    "gulp-sass": "^4.0.2",
    "gulp-sourcemaps": "^2.6.5",
    "jquery": "^3.4.1",
    "lazysizes": "4.1.5",
    "material-design-icons": "^2.1.3",
    "mini-css-extract-plugin": "^0.7.0",
    "node-sass": "^4.5.0",
    "popper.js": "^1.14.3",
    "postcss-flexibility": "^2.0.0",
    "postcss-loader": "^3.0.0",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.14.0",
    "terser-webpack-plugin": "^1.3.0",
    "webpack": "^4.35.3",
    "webpack-cli": "^3.3.5",
    "webpack-dev-server": "^3.7.2",
    "webpack-sources": "^0.1.0"
  },
  "dependencies": {
    "babel-preset-react": "^6.24.1"
  }
}`

**Comment by prestarocket** [comment]
i m working on it
