### ISSUE TITLE
A few improvements to consider/implement

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/classic-rocket#76]
**Keep prices in the product list on the bottom, makes it look more uniform.**
```
.product-description {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  height: 100%;
}
```

**Remove one unneccessary padding between products in 2column view.**
```
.product-miniature:nth-child(2n+1) {
    padding-right: 7.5px;
}
.product-miniature:nth-child(2n) {
    padding-left: 7.5px;
}
```

**Make left column slightly bigger on md view, improves usability a lot.**
```
col-12 col-md-4 col-lg-3
col-12 col-md-8 col-lg-9
```

**Other**
- Footer columns shouldn't be collapsible between 922px and 1190px.
- Make product list one column, maybe under 360px?

__

Best theme ever :-)

**Comment by prestarocket** [comment]
Footer columns shouldn't be collapsible between 922px and 1190px.
=> linked to responsive.js (responsive.min_width).
you can change this width and edit mixin media-breakpoint-desktop & media-breakpoint-mobile in themes/classic-rocket/_dev/css/partials/_mixins.scss
