### ISSUE TITLE
Image not showing on Internet Explorer

### ISSUE THREAD

**Issue by msaustral** [PrestaShop/classic-rocket#77]
Hi after done all the update of Webpack and dependencies, on IE the image are not been shown, on the console got this error:
![image](https://user-images.githubusercontent.com/46203943/62250024-daa3cb80-b3b9-11e9-9172-5696e4803f13.png)
 
![image](https://user-images.githubusercontent.com/46203943/62249966-b516c200-b3b9-11e9-8037-2b5679a7ad86.png)

![image](https://user-images.githubusercontent.com/46203943/62250015-d1b2fa00-b3b9-11e9-9ea9-3420ce7b31bf.png)

This is my package.json:

`{
  "name": "australpygb",
  "version": "1.0.0",
  "description": "Tema de Austral",
  "main": "index.js",
  "scripts": {
    "build": "webpack --mode production --progress --colors --debug --display-chunks",
    "watch": "webpack --mode development --progress --colors --debug --display-chunks --watch"
  },
  "author": "Ausral",
  "license": "AFL-3.0",
  "devDependencies": {
    "@babel/core": "^7.5.4",
    "ajv": "^6.9.1",
    "autoprefixer": "^9.4.4",
    "babel-loader": "^8.0.6",
    "bootstrap": "4.3.1",
    "bootstrap-touchspin": "^4.2.5",
    "css-loader": "^3.0.0",
    "expose-loader": "^0.7.3",
    "file-loader": "^4.0.0",
    "flexibility": "^1.0.5",
    "gulp": "^4.0.0",
    "gulp-autoprefixer": "^6.0.0",
    "gulp-replace": "^1.0.0",
    "gulp-sass": "^4.0.2",
    "gulp-sourcemaps": "^2.6.5",
    "jquery": "^3.4.1",
    "lazysizes": "4.1.5",
    "material-design-icons": "^2.1.3",
    "mini-css-extract-plugin": "^0.7.0",
    "node-sass": "^4.5.0",
    "popper.js": "^1.14.3",
    "postcss-flexibility": "^2.0.0",
    "postcss-loader": "^3.0.0",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.14.0",
    "terser-webpack-plugin": "^1.3.0",
    "webpack": "^4.35.3",
    "webpack-cli": "^3.3.5",
    "webpack-dev-server": "^3.7.2",
    "webpack-sources": "^0.1.0"
  },
  "dependencies": {
    "babel-preset-react": "^6.24.1"
  }
}
`

PrestaShop version 1.7.6

I did try on fresh installation and install the theme and it works, no idea what is not working!

**Comment by prestarocket** [comment]
I am still working on the update, the theme is not fully compatible 1.7.6

**Comment by msautral** [comment]
Hi I don't think it is a problem with Prestashop 1.7.6, if I download the theme and install it as it is on Github on 1.7.6 it works fine.

I think must be a problem with Jquery or any other dependency that I did update on the webpack by NPM.

It works fine on all browsers less IE, I have no idea where to start to find the issue!

**Comment by dangelion** [comment]
Same problem here. Any updates?

**Comment by prestarocket** [comment]
@dangelion @msaustral could you give an url to check plz ?

**Comment by dangelion** [comment]
@prestarocket you can check your demo online: https://demoprestashop.prestarocket.com/fr/

In console you get SCRIPT1028 (same as the screenshot posted by @msaustral). So you have no images and JS execution blocked. The result is our websites are broken
