### ISSUE TITLE
Faceted navigation not functional

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/classic-rocket#79]
Mobile:
- Arrows not aligned
- When clicking anything, it opens the last filter
- Price slider visible on page load

Desktop:
- Options not visible
- Cannot expand anything

![filtered2](https://user-images.githubusercontent.com/6097524/62292908-b43c6980-b467-11e9-9e6d-fb90cdf99ffb.JPG)

![filtered](https://user-images.githubusercontent.com/6097524/62292911-b56d9680-b467-11e9-892b-1fad60f3accc.JPG)

**Comment by prestarocket** [comment]
we are still working on...
facet will be ok
<img width="457" alt="Capture d’écran 2019-08-02 à 09 25 20" src="https://user-images.githubusercontent.com/899422/62352081-958daf80-b507-11e9-9fb4-023d4c32b2da.png">
