### ISSUE TITLE
This theme is not valid for Prestashop 1.7

### ISSUE THREAD

**Issue by johanlantz** [PrestaShop/classic-rocket#8]
Hi

First of all, I did testdrive the theme the day after it was published and to be honest it was the best news for Prestashop this year. I was thinking about trying to tweak the Classic theme myself and I really lack the skills and then this comes along and fixes almost all the issues. Big kudos for an amazing and important effort.

I have not done anything with Prestashop in a while so today I had some time and decided to install the 1.7.4.2 and the latest version of the classic-rocket.

However, when trying to install classic-rocket, I just get the "This theme is not valid for Prestashop 1.7" error message.
<img width="464" alt="screen shot 2018-09-01 at 18 27 31" src="https://user-images.githubusercontent.com/7461655/44947974-bb04cb80-ae15-11e8-8c22-f3acd00d41aa.png">

This is on a vanilla installations just downloaded from github of both Prestashop and the theme.

**Comment by prestarocket** [comment]
Hello,
Thx. Did you try to download the Zip of the theme ?

Le sam. 1 sept. 2018 à 19:35, johanlantz <notifications@github.com> a
écrit :

**Comment by thegrince** [comment]
Very quick answer because I have to go: not very sure but I thinks the issue was that the actual theme was a zip nested in the downloaded zip.

**Comment by johanlantz** [comment]
I just downloaded from here:
https://github.com/PrestaShop/classic-rocket/releases

The top one which should be for 1.7.4.x

When I unpack it does not seem nested:
<img width="617" alt="screen shot 2018-09-01 at 19 54 59" src="https://user-images.githubusercontent.com/7461655/44948604-f1941380-ae20-11e8-8b43-404d5f4fafe4.png">

**Comment by thegrince** [comment]
A bit different from mine. Maybe corrected since?
I am not familiar with github (my bad).
Also if I remember correctly (hum...) my upload limit was a problem:
https://stackoverflow.com/questions/9691057/php-apache-ajax-post-limit/9691395#9691395
![image](https://user-images.githubusercontent.com/19391261/44954030-fe564d00-ae9c-11e8-89d2-deb81e04cdda.png)
![image](https://user-images.githubusercontent.com/19391261/44954042-57be7c00-ae9d-11e8-9558-dd1d78ec92ac.png)

**Comment by johanlantz** [comment]
Don't think that is related

I tried unpacking the theme and upload it directly. Then just select "Use this theme" from the Themes menu. Then the error is different:
<img width="727" alt="screen shot 2018-09-02 at 16 25 03" src="https://user-images.githubusercontent.com/7461655/44957012-075f1280-aecd-11e8-8e6a-bd3ea5004035.png">

iirc I saw a mentioning about moving this module to the Prestashop repo or something similar? I guess this error is what is causing the install to fail as well?

**Comment by thegrince** [comment]
I hope the guys from PrestaRocket will be able to help cause I'm really not good as this :-\
Maybe you can try to extract ps_searchbarjqauto from the zip (/dependencies/modules/ps_searchbarjqauto) and install it independently?

**Comment by GuillaumeKadolis** [comment]
Download ps_searchbarjqauto from https://github.com/PrestaShop/ps_searchbarjqauto/releases
Install it, then install theme

**Comment by johanlantz** [comment]
I downloaded the module, got this error when trying to install it:
<img width="657" alt="screen shot 2018-09-03 at 10 41 32" src="https://user-images.githubusercontent.com/7461655/44976620-0e862f00-af66-11e8-8113-7b714117f580.png">

I unpacked and created a folder with the module name in the zip file and tried to reinstall but got the same error. Do not see any config file for the module but maybe that is not needed anymore?

Again, this is all on a vanilla installation of latest Prestashop. Not on a real shop, there are no customizations or anything, just a clean install so I am surprised I am not able to install the theme. 

I guess this should be reproducible for anyone?

**Comment by GuillaumeKadolis** [comment]
-_-' Ah there is an error in release name
unzip file, rename ps_searchbarjqauto-1.0.0 folder to ps_searchbarjqauto, zip folder to ps_searchbarjqauto.zip and install the module.

**Comment by johanlantz** [comment]
Still not installing. These are the names I have now:

<img width="309" alt="screen shot 2018-09-03 at 11 02 38" src="https://user-images.githubusercontent.com/7461655/44977710-05e32800-af69-11e8-926b-cf452fe0b11a.png">

<img width="207" alt="screen shot 2018-09-03 at 11 02 48" src="https://user-images.githubusercontent.com/7461655/44977715-08de1880-af69-11e8-9a72-f374a5e77b75.png">

<img width="292" alt="screen shot 2018-09-03 at 11 02 55" src="https://user-images.githubusercontent.com/7461655/44977722-0bd90900-af69-11e8-800b-b64b514da925.png">

**Comment by GuillaumeKadolis** [comment]
it work here with fresh install, i join you the module but it look like you have the same as me.
[ps_searchbarjqauto.zip](https://github.com/PrestaShop/classic-rocket/files/2344915/ps_searchbarjqauto.zip)
if you have ps_searchbarjqauto folder into module folder try to remove it, active debug, 
got to your module manager, press F12 to have navigator console, into console go to network, then install again, if you have error you should have more error on request reponse 
you need to look this line respond https://www.prestashop.local/adminXXXXXXX/index.php/module/import

**Comment by johanlantz** [comment]
Ok, big thanks.

Now I could install the module. I thought it needed to have an internal subfolder with the same name as the module, my bad, I knew that but was confused by the Prestashop error that was not so informative.

However, trying to install the theme using the zip file still failed. Same error.

If I unpack the theme manually and then select it in Theme and Logo, it seems to work fine.

So something might still be weird when installing from the zip but my immediate problem seems solved.

**Comment by prestarocket** [comment]
i will check this next week; i m still on vacation...

**Comment by manfield** [comment]
Everything works as expected, on the latest PS version.
You need to compile assets inside _dev folder (use webpack-cli version 2.x and node 7.x).
Then you need to download the ps_searchbarjqauto.zip and be sure the folder name, once decompressed it is correct. 
There you go, theme installed and full working.
Thanks to the author.
