### ISSUE TITLE
[Feature request] Move faceted OK button to the sidebar header

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/classic-rocket#80]
It would be good to move the OK button to the siderbar header, next to X icon.

When there are more filters than page height, OK button scrolls with them. This way, it would be visible all the time and when the user reaches the end with his selection, he just clicks OK and doesnt have to scroll back to the top again.

![filtered](https://user-images.githubusercontent.com/6097524/62293174-4d6b8000-b468-11e9-9b16-6d6b38d72f91.JPG)

**Comment by prestarocket** [comment]
it s in the bottom now.
