### ISSUE TITLE
[Improvement] Passive event listener

### ISSUE THREAD

**Issue by dosbiner** [PrestaShop/classic-rocket#82]
fix warning reported by Google Chrome Dev tool: Audits
source:
- https://www.youtube.com/watch?v=DJYpXxWqvmo
- https://caniuse.com/#feat=passive-event-listener

**Comment by prestarocket** [comment]
could you make a PR on develop branch ?

**Comment by MockoB** [comment]
Hi @prestarocket, I saw you closed the issue, but are the passive event listeners added to the theme? Because it is a must have addition I believe.
Thanks

**Comment by prestarocket** [comment]
i need more info and you can send a PR; which part of code is responsible for these warnings ?

**Comment by MockoB** [comment]
Unfortunately I'm not developer @prestarocket, and I can't make a PR. But here is a screenshot of google lighthouse recommendation: https://ibb.co/Lz7HGrt
you could easily check what needs to be changed in the template by yourself.

And here is interesting article, where you could find more info concerning the topic: https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md

**Comment by prestarocket** [comment]
it's cause by third party plugins like slick slider
