### ISSUE TITLE
delivery-option class missing

### ISSUE THREAD

**Issue by damiweb** [PrestaShop/classic-rocket#84]
Many shipping modules use CSS delivery-option class to hook into selected shipping option.

https://github.com/PrestaShop/classic-rocket/blob/2065f9c0f86fc6606d96f162d2103d112c64677b/templates/checkout/_partials/steps/shipping.tpl#L44

**Comment by prestarocket** [comment]
on branch developper ?

**Comment by jdziewonski** [comment]
> on branch developper ?
yes

**Comment by prestarocket** [comment]
we use now the default html structure because too may pbs with shipping modules...
