### ISSUE TITLE
If you click two or more times add to cart button, crazy

### ISSUE THREAD

**Issue by acentoweb** [PrestaShop/classic-rocket#85]
reproduction:
![https://raw.githubusercontent.com/acentoweb/bugs/master/bugps.gif](https://raw.githubusercontent.com/acentoweb/bugs/master/bugps.gif)

If you remove

```
&&n.remove()
```

from theme.js the problem is solved

**Comment by prestarocket** [comment]
could you try here :
https://demoprestashop.prestarocket.com/art/3-13-affiche-encadree-the-best-is-yet-to-come.html#/19-dimension-40x60cm

**Comment by acentoweb** [comment]
Thanks @prestarocket . Same results

!(ps)[https://raw.githubusercontent.com/acentoweb/bugs/master/bug2ps.gif]

**Comment by acentoweb** [comment]
Perhaps, a good idea would be:
- if you click button: attr disabled
- When you close blockcart or click continue, enabled 
?¿
Thanks

**Comment by prestarocket** [comment]
it s not linked to the theme, same pb with classic theme : http://demo.prestashop.com

**Comment by kpodemski** [comment]
but you can fix it by making add to cart button disabled after first click, and enabling it after updatedCart

**Comment by prestarocket** [comment]
done

**Comment by matks** [comment]
> it s not linked to the theme, same pb with classic theme : http://demo.prestashop.com

Hi @prestarocket I'm sorry but I fail to reproduce the behavior 🤔 can you please tell me exactly what I must do to see the bug and what is expected ?

Right now on http://demo.prestashop.com/#/en/front:
- if I click ton 'add to cart' the modal opens
- if I click on 'continue shopping' the modal disappears
- if I click on 'add to cart' while the modal is opened, the modal disappears too

I tried a very quick double-click too, I got nothing that looks weird

**Comment by prestarocket** [comment]
> > it s not linked to the theme, same pb with classic theme : http://demo.prestashop.com
> 
> Hi @prestarocket I'm sorry but I fail to reproduce the behavior 🤔 can you please tell me exactly what I must do to see the bug and what is expected ?
> 
> Right now on http://demo.prestashop.com/#/en/front:
> 
> * if I click ton 'add to cart' the modal opens
> * if I click on 'continue shopping' the modal disappears
> * if I click on 'add to cart' while the modal is opened, the modal disappears too
> 
> I tried a very quick double-click too, I got nothing that looks weird

click like a crazy man before modal opens :)

**Comment by matks** [comment]
> > > it s not linked to the theme, same pb with classic theme : http://demo.prestashop.com
> > 
> > 
> > Hi @prestarocket I'm sorry but I fail to reproduce the behavior 🤔 can you please tell me exactly what I must do to see the bug and what is expected ?
> > Right now on http://demo.prestashop.com/#/en/front:
> > 
> > * if I click ton 'add to cart' the modal opens
> > * if I click on 'continue shopping' the modal disappears
> > * if I click on 'add to cart' while the modal is opened, the modal disappears too
> > 
> > I tried a very quick double-click too, I got nothing that looks weird
> 
> click like a crazy man before modal opens :)

OK like reaaaaaaal crazy then 😄 I got it

**Comment by matks** [comment]
I submitted the bug https://github.com/PrestaShop/PrestaShop/issues/15483 for classic theme 😉
