### ISSUE TITLE
Minor css issue on add to cart confirm

### ISSUE THREAD

**Issue by johanlantz** [PrestaShop/classic-rocket#9]
Continue shopping button is outside of the container. 

iPhone 6 screenshot. 

![435827ec-67f0-4561-a4cc-df0c734d7a04](https://user-images.githubusercontent.com/7461655/44984586-94fa3b00-af7d-11e8-96f9-796ddae3cd2f.png)

**Comment by prestarocket** [comment]
ok thx; i will fix it

**Comment by johanlantz** [comment]
Out of curiosity, is there a commitment from Prestashop to make this theme the default one in 1.7.5.0? I got that impression at one point?

I just hope it will keep getting worked on.

**Comment by prestarocket** [comment]
No, it will no be the default theme in 1.7.5; but we will update it and add improvements.

**Comment by PrestaShark** [comment]
Adding responsive classes to any buttons is nice in that cases. `btn btn-primary col-12 col-md-6`

**Comment by duGuillaume** [comment]
it's useless to add col-12

**Comment by duGuillaume** [comment]
@PrestaShark 
col-12 is implicit if you are using col-sm-x
or col-sm-12 is implicit if you are using col-md-x ....
col-12 use usefull only if you are using it alone
